all:
	cd e1000e-1.3.10a-DNA/src; make
	cd igb-3.1.16-DNA/src; make
	cd ixgbe-3.3.9-DNA/src; make

clean:
	cd e1000e-1.3.10a-DNA/src; make clean
	cd igb-3.1.16-DNA/src; make clean
	cd ixgbe-3.3.9-DNA/src; make clean

